### ISSUE TITLE
[BUG] Incorrect base URL/ sitemap URL detection

### ISSUE THREAD

**Issue by Mainbird** [eliashaeussler/typo3-warming#431]
### TYPO3 version

11.5.30

### PHP version

8.1.21

### Extension version

0.5.3

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

macOS 13.4.1

### Current behavior

cli command take use of the wrong TYPO3 context base/ sitemap URL

### Expected behavior

cli command take use of the correct context base/ sitemap URL like development, stage/ testing or production 

### Steps to reproduce

I think I did nothing special so far, but I am using ddev (1.22.1) for development.

1. ddev composer req eliashaeussler/typo3-warming:^0.5 -W
2. sitemap URL is configured by site config like:

```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
```
      
3. ./vendor/bin/typo3 warming:cachewarmup -s main

### Additional context

Hi Elias,

thanks a lot for your nice extension. :)

I am not sure if I miss something, but if I start the sitemap crawling process via cli inside the ddev web container then I thought that your extension will grab the correct URL by the current TYPO3 context and will start crawling the corresponding sitemap URLs. I am not completely sure, but I think this did work initially, but after some more cli runs, the cli command take care of the wrong base/ sitemap URL and have started crawling of the production sitemap URLs.

I think this is not the expected behaviour or am I wrong? 

The relevant parts of my site config looks nearly like this:

```
base: 'https://example.de/'
baseVariants:
  -
    base: 'https://example.ddev.site/'
    condition: 'applicationContext == "Development/Ddev"'
  -
    base: 'https://stage.example.de/'
    condition: 'applicationContext == "Testing/Stage"'
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
```

and if I trigger the cli command inside the ddev web container with:

`./vendor/bin/typo3 warming:cachewarmup -s main`

The crawling process will start crawling URLs of the production domain like:

https://example.de/abc

instead of:

https://example.ddev.site/abc

Did I miss something or do I have to take care of the correct TYPO3 context somehow?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @Mainbird, thanks for your issue. Unfortunately, I cannot reproduce this in my setup.

Given the following site config:

```yaml
base: 'https://www.example.com/'
baseVariants:
  -
    base: 'https://typo3-ext-warming.ddev.site/'
    condition: 'applicationContext == "Development/DDEV"'
```

When running `ddev exec .Build/bin/typo3 warming:cachewarmup -s main`, the correct base URL (`https://typo3-ext-warming.ddev.site/`) is resolved.

Can you please run `ddev exec env | grep TYPO3_CONTEXT` to check if the application context is properly set in your DDEV environment? It should output something like `TYPO3_CONTEXT=Development/DDEV`.

Also keep in mind that resolved sitemaps are cached in `var/cache/code/core/tx_warming.php`. If you've changed the application context after running cache warmup the first time, you need to clear caches after you've changed the application context. This will enforce a fresh sitemap resolving, taking the modified application context into account.
